### ISSUE TITLE
Updates, probleme, Lizenz, Sicherheit

### ISSUE THREAD

**Issue by FelixKlauke** [mtoensing/Docker-Minecraft-PaperMC-Server#1]
Hey,

auf deinem Blog kommen ja viele Nachfragen nach Problemen, Updates, aktuellen Versionen und so weiter. Als du diese wirklich frühe Version meines Images übernommen hast waren auch mir viele Probleme noch gar nicht klar oder aufgefallen. Zum Beispiel nutzt du aktuell den Root User.

So fehlen deinen run scripts zum Beispiel die TTY's, sodass man sie eigentlich kaum benutzen kann. Außerdem solltest du dir mal angucken, dass du eine neuere Java Version für die Runtime benutzt. Dieses komische alte Java Dingens da gibt es mittlerweile vernünftig direkt vom OpenJDK. Auch meinen Healtcheck kannst du gerne einbauen.

Momentan baust du auf Java 11 und "runst" unter einem 8er. 

Du kannst dir gerne meine aktuelle Version ansehen, an der ich wirklich viel verändert habe.
https://github.com/FelixKlauke/paperspigot-docker

Auch würde ich gerne deine Meinung hören. Findest du den Ansatz mit einem Volume oder mehreren besser? Ich werde vermutlich wieder auf ein Volume zurückbauen, ich habe bei mir mittlerweile einige Befürchtungen durch die Unmengen von Sym Links :)

Wenn du Fragen oder Probleme hast kannst du dich gerne an mich wenden.

Aber schöner Blog Artikel!

**Comment by mtoensing** [comment]
hey, hey, Nicht schließen. Da kommt noch einiges. Erstmal vielen Danke für die Hinweise und: Sorry. Ja, ich habe dein Dockerimage damals als Basis genommen und so viel rausgestrichen bis ich es irgendwann verstanden geglaubt habe. Ich passe mein Image an, gebe dir Credit auf deines. Ich werde allerdings weiterhin ziemlich schlicht unterwegs sein mit wenig Eingriffmöglichkeiten von außen. Ich glaube, dass es besser ist, einen Weg zu gehen, der funktioniert und nicht zu viele Türen (ENV) zu öffen für die Leute, die noch weniger Ahnung haben als ich. 

Deswegen auch ein Volume. Ich habe die Anleitung geschrieben für einen Vanilla Server. Keine Ahnung, was Plugins da für Probleme mit haben. Deswegen bleibt das auch hart drin. 

Die .sh Scripte sind eigentlich nur für mich zum testen bevor es auf Dockerhub geht. Die werden nicht vom Image genutzt. Und das mit JAVA 8... das ist schon ein dummer Fehler meinerseits. Auf 11 builden aber auf 8 laufen lassen. Geil. Danke. Es kommt gleich ein Update, das sich dann auch selber nutzen werde.

**Comment by mtoensing** [comment]
Blogartikel ist ebenfalls angepasst: https://marc.tv/anleitung-stabiler-minecraft-server-synology-nas/

**Comment by mtoensing** [comment]
So, jetzt kannst es ggf. schließen wenn ich nichts vergessen habe.

**Comment by FelixKlauke** [comment]
Hey,

danke dafür! Wenn du nur einen Vanilla Server betreiben willst, dann solltest du dir bewusst sein, dass momentan Paper Spigot als Server benutzt wird (https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/blob/master/Dockerfile#L8), ist das in deinem Sinne?

Den simplen Ansatz verstehe ich, ich glaube auch dass meine Version sich da zum schlechteren entwickelt hat.

**Comment by mtoensing** [comment]
Ok, ich nutze natürlich nicht den "echten" Vanilla Server sondern Paper weil der sonst weder auf dem Raspberry Pi läuft und auch nicht auf dem Synology NAS. Erst Paper macht es spielbar. 

Mit Vanilla meinte ich ohne Plugins und spezielle Einstellungen. Läuft ganz gut: https://mc.marc.tv
