### ISSUE TITLE
How do I acess previous images. 

### ISSUE THREAD

**Issue by Jxulian1** [mtoensing/Docker-Minecraft-PaperMC-Server#104]
I want to use the image docker 'pull marctv/minecraft-papermc-server:1.20.2.' when i try I get a error that says I can't pull the image

![image](https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/assets/106756844/d794bb0f-426a-4c15-a7c4-53d8eb44bb52)

**Comment by mtoensing** [comment]
There is no 1.20.2 only 1.20
