### ISSUE TITLE
Couldn't send command in terminal through "docker attach x"

### ISSUE THREAD

**Issue by RiftRoar** [mtoensing/Docker-Minecraft-PaperMC-Server#107]
Hello !
Thanks for this useful project, it's really helpful.
I've got some issue while trying to access console.
The command "docker attach x" seems to work well, but i couldn't send any command.
I've got the output of the server, but when i try to send input and press Enter, nothing happens.
Do you have any idea ?
Thanks in advance !

**Comment by b2un0** [comment]
do you start the container with `-it` ?

or the compose service with:
```yaml
stdin_open: true
tty: true
```
