### ISSUE TITLE
Accessing Older Versions

### ISSUE THREAD

**Issue by jshackney** [mtoensing/Docker-Minecraft-PaperMC-Server#111]
It's very possible I am missing this. I want to download version 1.20.4, or 1.19.2. What is the correct incantation to do this?

I've tried 

-e VERSION=1.20.4, and
marctv/minecraft-papermc-server:1.20.4

I apologize if I have missed the correct method.

**Comment by mtoensing** [comment]
Hi, we only provide the latest version for now. This might change in the future.

**Comment by b2un0** [comment]
should now be possible,
take a look
https://hub.docker.com/r/marctv/minecraft-papermc-server/tags
