### ISSUE TITLE
Can't send commands

### ISSUE THREAD

**Issue by NickTheOnlyNeko** [mtoensing/Docker-Minecraft-PaperMC-Server#118]
whenever i write "docker attach mcserver" i enter the console but i can't enter any kind of command i've tried "/op [Name here]", "op [Name here]", "/stop", "stop", "/kill [Name here]", "kill [Name here]". pls fix

**Comment by b2un0** [comment]
You don’t run the container with

stdin_open: true
 tty: true

…

Pls fix

**Comment by NickTheOnlyNeko** [comment]
> You don’t run the container with
> 
> stdin_open: true tty: true
> 
> …
> 
> Pls fix

i don't even know what that is

**Comment by b2un0** [comment]
Please ask a AI or RTFM
