### ISSUE TITLE
Problem with server 

### ISSUE THREAD

**Issue by Snurrebuss** [mtoensing/Docker-Minecraft-PaperMC-Server#14]
I hosted a server for me and my friends on my synology ds1019+ but when they try to join it only says
 Here is a link to a picture: https://ibb.co/6P78Bn0

**Comment by mtoensing** [comment]
Can you connect from within your own network?

**Comment by Snurrebuss** [comment]
yes

**Comment by mtoensing** [comment]
In that case this is not a problem with the server but with the port forwarding in your router.
