### ISSUE TITLE
custom pid and gid

### ISSUE THREAD

**Issue by seriousm4x** [mtoensing/Docker-Minecraft-PaperMC-Server#15]
It'd be nice to set custom pid and gid id's. The data is created as root user no matter what environment variables you declare.
Also specifing user and group in Dockerfile with groupadd/useradd doesn't seem to work.

**Comment by mtoensing** [comment]
Great. Do you know how to do this? As you might know I use the openjdk:11 image. Can you provide a pull request? Or shouldn't this work because I use this image as base?

**Comment by j4c3** [comment]
Not 100% about that image specifically, but in theory, you run a script as the entry point.

```
#!/bin/bash
set -e

DOCKER_USER='dockeruser'
DOCKER_GROUP='dockergroup'

if ! id "$DOCKER_USER" >/dev/null 2>&1; then
    echo "First start of the docker container, start initialization process."

    USER_ID=${PUID:-9001}
    GROUP_ID=${PGID:-9001}
    echo "Starting with $USER_ID:$GROUP_ID (UID:GID)"

    groupadd -f -g $GROUP_ID $DOCKER_GROUP
    useradd --shell /bin/bash -u $USER_ID -g $GROUP_ID -o -c "" -m $DOCKER_USER

    chown -vR $USER_ID:$GROUP_ID $APP_PATH
    chmod -vR ug+rwx $APP_PATH
    chown -vR $USER_ID:$GROUP_ID $DATA_PATH
fi

export HOME=/home/$DOCKER_USER
exec <<old entrypoint>>
```

**Comment by mtoensing** [comment]
Cool. You could make a pull request if you like. Isn't this possible without a shell script with changes only in the Dockerfile?
