### ISSUE TITLE
None of my friends can connect

### ISSUE THREAD

**Issue by Snurrebuss** [mtoensing/Docker-Minecraft-PaperMC-Server#16]
I made a minecraft server on my nas but none of my friends can connect. I can connect but they cant. How do i fix this?
Here is a picture of thr error for them
![31C7S](https://user-images.githubusercontent.com/68329940/104837865-c5757200-58b7-11eb-9960-1044c567026e.jpg)

**Comment by VandenOstende** [comment]
It has something to do with your router. It needs to accept incoming traffic. Not all ISP allow that. 

Verstuurd vanaf mijn iPhone

**Comment by Snurrebuss** [comment]
How dp i fix the router?

**Comment by mtoensing** [comment]
This challenge has nothing to do with this docker container. You successfully installed a working server on your NAS. Contratulations! If you want to open your server to the internet, you have to open the port 25565 of your NAS to the internet. Even more important: you server needs a fixed public ip or url where your friends can connect. Your local ip does not matter here. There are too many configurations and combinations of routers and ISPs to write a tutorial.
