### ISSUE TITLE
Create 1.15 tag to prevent auto-updates

### ISSUE THREAD

**Issue by XDGFX** [mtoensing/Docker-Minecraft-PaperMC-Server#2]
It would be great if there was a 1.15 tag as well as 1.14 and 1.13 - that way when a new version comes out the server won't automatically update if set to stay on 1.15!

**Comment by mtoensing** [comment]
Good idea!

**Comment by mtoensing** [comment]
https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/tree/1.15
https://hub.docker.com/r/marctv/minecraft-papermc-server/tags

Done.
