### ISSUE TITLE
Recommendation to move shell files into Makefile

### ISSUE THREAD

**Issue by leothelocust** [mtoensing/Docker-Minecraft-PaperMC-Server#20]
I was just looking into the shell files in the root of the project, and they seem to align pretty perfectly with the new Makefile.

For example:

`build_docker.sh` which just contains:
```text
docker build -t marctv/minecraft-papermc-server .
```
can be moved into the Makefile:
```Makefile
.PHONY: build_docker
build_docker: ## Docker build in prep for updating Docker Hub ## 
	@echo "Building..."
	docker build -t marctv/minecraft-papermc-server .;
```
And then later ran by simply typing:
```sh
make build_docker
```

If you like that idea, I can create a PR to implement this and remove the shell files and update the README.

Let me know, thanks

**Comment by mtoensing** [comment]
Yes, would be great!

**Comment by leothelocust** [comment]
@mtoensing what is the purpose of rcon-cli? I'm not familiar.  

When I try to run ./rcon-cli.sh to see the output, i'm seeing an error:
![image](https://user-images.githubusercontent.com/4381907/105085029-c98ec480-5a5c-11eb-89c4-bcf998f9aede.png)

Thoughts?

**Comment by leothelocust** [comment]
I'm getting the impression the purpose of it is negated by the `docker attach` command? as it appears to just allow game commands to be entered?

**Comment by mtoensing** [comment]
rcon is important for communication from the outside. I use it to read information from my running server from my webserver.

**Comment by mtoensing** [comment]
Yes, only game commands are allowed on rcon. https://wiki.vg/RCON

**Comment by leothelocust** [comment]
Maybe I'm missing something in order for RCON to work? is rcon turned on by default on 25575?

**Comment by mtoensing** [comment]
I use rcon on my setup with a php script. So it works in the container
