### ISSUE TITLE
Stop the server gracefully with Docker

### ISSUE THREAD

**Issue by svenmauch** [mtoensing/Docker-Minecraft-PaperMC-Server#26]
Hi, thank you for maintaining this project!

I was wondering if there is a way to gracefully stop the server using docker. If I'm not mistaken, ```docker stop``` sends a SIGTERM to the container, but when inspecting the server output using ```docker attach``` it seems there is not the usual output I expect from a stopping Minecraft server (saving world, stopping server).

Am I correct in assuming that this does not stop the server gracefully? If so, would this be an issue that could be fixed by this project or should it be directed at PaperMC?

**Comment by mtoensing** [comment]
I think the server is stopped gracefully if the container is stopped or restarted. Never had an issue with that.

**Comment by svenmauch** [comment]
Thanks for the quick respoinJust took another look and it seems the server does not stop gracefully. Recently build blocks are lost and the server doesn't stop by unloading plugins and kicking users with the message "server is shutting down".

![grafik](https://user-images.githubusercontent.com/24568451/118887351-88b79700-b8fa-11eb-9c69-08406c63348f.png)

I would appreciate a quick look if my compose file is missing anything important or if you have any idea what's causing the different behavior.

```version: '3.3'
services:
  minecraft:
    container_name: minecraft
    image: marctv/minecraft-papermc-server:1.16
    environment:
      MEMORYSIZE: 6G
      TZ: Europe/Berlin
    volumes:
      - './minecraft-data:/data:rw'
    ports:
      - '25565:25565'
    stdin_open: true
    tty: true```

I'll try and dig a bit deeper in the meantime.

**Comment by mtoensing** [comment]
The compose file looks okay.

**Comment by svenmauch** [comment]
I took a closer look and found out the server was not running as pid 1, therefore not honoring SIGKILL.

It seems this problem only occurs when pulling ``marctv/minecraft-papermc-server:1.16`` from Docker Hub. After pulling the master branch from GitHub, everything works as expected.

Docker Hub:

![grafik](https://user-images.githubusercontent.com/24568451/119027438-9cb8d280-b9a6-11eb-99c5-7cc216f7f30c.png)

GitHub:

![grafik](https://user-images.githubusercontent.com/24568451/119027138-49df1b00-b9a6-11eb-8d78-67e226c1644f.png)

Could there be something wrong with the prebuilt images?

**Comment by mtoensing** [comment]
The images are build on Docker Hub with GitHub as the source. Any idea what could cause this?

**Comment by mtoensing** [comment]
done
