### ISSUE TITLE
ERRO 1.17

### ISSUE THREAD

**Issue by Danielkoscheck** [mtoensing/Docker-Minecraft-PaperMC-Server#30]
![image](https://user-images.githubusercontent.com/83882821/122847382-f716bd00-d2dd-11eb-9e74-cff503f4211d.png)

**Comment by Danielkoscheck** [comment]
I solved adding permission folder for everyone. How to migrate maps 1.16 to 1.17 ? Move folders ...world, nether ?

**Comment by mtoensing** [comment]
Immigrated just by updating the container for my server. Any other one with a problem?

**Comment by Danielkoscheck** [comment]
I'm still testing it, so far I've put folder permission. The error appeared when I deleted the data folder and recreated it

**Comment by mtoensing** [comment]
"Latest" contains the final version of 1.17.=)
