### ISSUE TITLE
openjdk:17-alpine not compatible with Minecraft 1.18 due to it using the 17-ea version of Java

### ISSUE THREAD

**Issue by ilektron** [mtoensing/Docker-Minecraft-PaperMC-Server#34]
https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/blob/cb710a7b160e81a7b41420cb5451d7dae008df05/Dockerfile#L4

Experienced a server crash due to the openjdk:17-alpine docker image not using the actual 17 release version of java at this time

**Comment by mtoensing** [comment]
See #33 Branch "1.18" or "beta" works fine. There is already a "1.18" image on Docker Hub: 

docker pull marctv/minecraft-papermc-server:beta 

**Experimental test builds for 1.18. Use with extreme caution! Backups are mandatory.**

**Comment by ilektron** [comment]
While I found it ran fine for some cases, [I experienced a crash](https://github.com/PaperMC/Paper/issues/7062#event-5730904461) that turned out to be because the openjdk:17-alpine build uses the 17-ea version of Java which is missing some functions that were added for the actual 17 release version. The openjdk:17-alpine image is kind of in limbo right now, see [http://jdk.java.net/17/](http://jdk.java.net/17/)

**Comment by mtoensing** [comment]
Do you have a better idea which image is better? Maybe a Pull Request?

**Comment by ilektron** [comment]
I couldn't really find one at this time, so I built my own java docker image with version of java that Paper recommends, ilektron/paperjdk. I'll test stability today and if everything looks good I'll work on a pull request in the next day that just changes the jdk image.

**Comment by mtoensing** [comment]
Thanks @josxha

**Comment by josxha** [comment]
Hi @mtoensing, i just wanted to let you know that while the beta image on Docker hub uses now the release version of java 17, it seems that the 1.18 image still uses the incompatible early access java version.

See: https://hub.docker.com/layers/marctv/minecraft-papermc-server/1.18/images/sha256-1785408f5c500a76182daa93f08b73e9ad7d67d6061a7d5693ae5b41b9428af6?context=explore

**Comment by josxha** [comment]
![image](https://user-images.githubusercontent.com/34318751/145303220-9792bda1-83a9-416e-91c3-d7768efa6370.png)

**Comment by mtoensing** [comment]
Maybe a caching issue? It seems okay now

**Comment by RuofengX** [comment]
Still not work now. I am planning to use onenjdk-17 instead

**Comment by mtoensing** [comment]
Did you try the "latest" tag?

**Comment by josxha** [comment]
@RuofengX @mtoensing I agree, the image runs fine
