### ISSUE TITLE
IMPORTANT MESSAGE: SECURITY VULNERABILITY IN JAVA EDITION

### ISSUE THREAD

**Issue by viperdriver2000** [mtoensing/Docker-Minecraft-PaperMC-Server#38]
update to 1.18.1 ?

https://www.minecraft.net/sv-se/article/important-message--security-vulnerability-java-edition

GAME SERVER 
If you’re hosting your own Minecraft: Java Edition server, you'll need to take different steps depending on which version you’re using, in order to secure it.

1.18: Upgrade to 1.18.1, if possible. If not, use the same approach as for 1.17.x:

1.17: Add the following JVM arguments to your startup command line: 
-Dlog4j2.formatMsgNoLookups=true

**Comment by dogederp** [comment]
Security issue has already been patched

**Comment by mtoensing** [comment]
Already taken care of in #36
