### ISSUE TITLE
Can't update Paper version

### ISSUE THREAD

**Issue by JonathanAlumbaugh** [mtoensing/Docker-Minecraft-PaperMC-Server#41]
Hey there, thanks for the awesome Minecraft server docker image! It runs so smoothly on a NAS and is really easy to set up! Right now I'm just having a little trouble updating, when I run `icanhasbukkit` I get this output saying I'm 60 versions behind:

![image](https://user-images.githubusercontent.com/9826603/152528811-10295759-cad3-4ed3-93fc-171fd462554f.png)

I've redownloaded from docker, stopped the container, reset, and started again but get the same output. I'm running this on a Synology DS920+ using the docker package in DSM. Any assistance would be greatly appreciated!

**Comment by mtoensing** [comment]
Thank you for bringing this to my attention. Caching was too aggressive. Try again in an hour to update your containers.

**Comment by JonathanAlumbaugh** [comment]
Perfect, thank you!

![image](https://user-images.githubusercontent.com/9826603/152540511-a09ee3ae-f3a6-410b-8dad-dae864f0ac51.png)
