### ISSUE TITLE
Container shuts itself down on ssh disconnect.

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [mtoensing/Docker-Minecraft-PaperMC-Server#44]
Im using the container image to run a papermc server on a vps using ssh. When my client connection crashes (for example if im attached to the container in the background via ssh and my wifi disconnects) The container itself stops and deletes itself. It works fine in the background if i disconnect from the container using ctrl p + ctrl q. Starting command:

```bash
docker run \
	--rm \
	--name vanilla-18 \
	-e MEMORYSIZE='4G' \
	-v /path/to/data:/data:rw \
	-p 1.1.1.1:19132/tcp -p 1.1.1.1:19132:19132/udp -p 1.1.1.1:25565:25565/tcp -p 1.1.1.1:25565:25565/udp \
	-ti marctv/minecraft-papermc-server:latest;
```
Changed the path and ip address for privacy but those are not related to the issue pretty sure. Is this an issue with the --rm flag?

**Comment by mtoensing** [comment]
Hi,

yes, rm removes the container when it shuts down.

**Comment by TranquillyUnpleasant** [comment]
The issue is that its shutting down on ssh disconnect, wheras my other containers that dont have --rm dont even shut it down if i disconnect while being attached.

**Comment by mtoensing** [comment]
What does the log tell you? This has nothing to do with the container but with docker in general

**Comment by TranquillyUnpleasant** [comment]
The log doesnt actually shut down the minecraft server, it just crashes when my ssh disconnects, and this issue doesnt happen on my other containers which are running directly via alpine-linux images.

**Comment by mtoensing** [comment]
Maybe the log tells you why the server shuts down. Again: this is a docker thing and not something related to this container. Maybe there are missing permissons for the mounted folders and other problems that can happen. The container works and this is no bug.
