### ISSUE TITLE
OpenMediaVault "Failed to download original jar"

### ISSUE THREAD

**Issue by gameinthebox** [mtoensing/Docker-Minecraft-PaperMC-Server#46]
Total docker newb here, so I appreciate any assistance! Struggling to work out what seems to me like a file permissions issue:

OMV ver 5.6.26.1
Docker ver 5:20.10.14-4-0-debian-buster
Portainer ver 2.11.1 

Created a CIFS share in order to have the container run on a separate disk than my OMV/Docker installation, which appears to authenticate without issue. Starting the container prompts a quick shutdown with the docker logs below. Executing ls -l on the directory shows that the corresponding user has read/write/edit access as well, so I'm not sure where to turn here.

Portainer is able to successfully deploy the container if I do not specify the volume, which is a problem when i'm trying to direct the volume to a different drive with the CIFS share. Should I be using "Bind" instead of "Volume" for the host path?

docker logs:

> First start of the docker container, start initialization process.
> Starting with 9001:9001 (UID:GID)
> changed ownership of '/opt/minecraft/paperspigot.jar' to 9001:9001
> changed ownership of '/opt/minecraft/docker-entrypoint.sh' to 9001:9001
> changed ownership of '/opt/minecraft' to 9001:9001
> mode of '/opt/minecraft' changed to 0775 (rwxrwxr-x)
> mode of '/opt/minecraft/paperspigot.jar' changed to 0774 (rwxrwxr--)
> mode of '/opt/minecraft/docker-entrypoint.sh' changed to 0777 (rwxrwxrwx)
> changed ownership of '/data/.DS_Store' to 9001:9001
> changed ownership of '/data/._.DS_Store' to 9001:9001
> changed ownership of '/data/data' to 9001:9001
> changed ownership of '/data' to 9001:9001
> Failed to download original jar
> java.nio.file.AccessDeniedException: /data/cache
> 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
> 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
> 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
> 	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
> 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
> 	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
> 	at io.papermc.paperclip.DownloadContext.download(DownloadContext.java:47)
> 	at io.papermc.paperclip.Paperclip.setupClasspath(Paperclip.java:63)
> 	at io.papermc.paperclip.Paperclip.main(Paperclip.java:28)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at io.papermc.paperclip.Main.main(Main.java:26)

OMV syslogs:

> kernel:   [53825.412297] CIFS: Attempting to mount //192.168.1.69/ffminecraft
> smbd[25293]: [2022/04/05   12:11:10.034544,  2]   ../source3/param/loadparm.c:2805(lp_do_section)
> smbd[25293]:   Processing section   "[ffminecraft]"
> smbd[25293]: [2022/04/05   12:11:10.035156,  2]   ../source3/param/loadparm.c:2805(lp_do_section)
> smbd[25293]: [2022/04/05   12:11:10.036556,  2]   ../source3/auth/auth.c:316(auth_check_ntlm_password)
> smbd[25293]:   check_ntlm_password:  authentication for user [FFMinecraft] ->   [FFMinecraft] -> [ffminecraft] succeeded
> smbd[25293]: [2022/04/05   12:11:10.039332,  2]   ../source3/smbd/service.c:849(make_connection_snum)
> smbd[25293]:    (ipv4:192.168.1.69:55502) connect to   service ffminecraft initially as user ffminecraft (uid=1003, gid=100) (pid   25293)
> smbd[25293]: [2022/04/05   12:11:10.039913,  2]   ../source3/smbd/dosmode.c:136(unix_mode)
> smbd[25293]:   unix_mode(.) inheriting from .
> smbd[25293]: [2022/04/05   12:11:10.039970,  2]   ../source3/smbd/dosmode.c:161(unix_mode)
> smbd[25293]:   unix_mode(.) inherit mode 42777
> smbd[25293]: [2022/04/05   12:11:10.041056,  2]   ../source3/smbd/dosmode.c:136(unix_mode)
> smbd[25293]:   unix_mode(.) inheriting from .
> smbd[25293]: [2022/04/05   12:11:10.041100,  2]   ../source3/smbd/dosmode.c:161(unix_mode)
> smbd[25293]:   unix_mode(.) inherit mode 42777
> smbd[25293]: [2022/04/05   12:11:10.042067,  2]   ../source3/smbd/dosmode.c:136(unix_mode)
> smbd[25293]:   unix_mode(.) inheriting from .
> smbd[25293]: [2022/04/05   12:11:10.042184,  2]   ../source3/smbd/dosmode.c:161(unix_mode)
> smbd[25293]:   unix_mode(.) inherit mode 42777
> smbd[25293]: [2022/04/05   12:11:10.043476,  2]   ../source3/smbd/dosmode.c:136(unix_mode)
> smbd[25293]:   unix_mode(.) inheriting from .
> smbd[25293]: [2022/04/05   12:11:10.043593,  2]   ../source3/smbd/dosmode.c:161(unix_mode)
> smbd[25293]:   unix_mode(.) inherit mode 42777
> containerd[500]:   time="2022-04-05T12:11:10.082090488-04:00" level=info   msg="starting signal loop" namespace=moby   path=/run/containerd/io.containerd.runtime.v2.task/moby/6bcb4b27b848a83531e304b15d8c082766969a270390480aecaaa1e770644933   pid=10224

**Comment by mtoensing** [comment]
"AccessDeniedException: /data/cache" 
This is a permission problem. It will work if docker has full access to the mounted folders
