### ISSUE TITLE
arm64 images

### ISSUE THREAD

**Issue by automate-this** [mtoensing/Docker-Minecraft-PaperMC-Server#52]
Hey. Would it be possible to also release arm64 images?

**Comment by mtoensing** [comment]
Yes. Tell me how :)

**Comment by automate-this** [comment]
I am relatively new to docker, but since your base image "docker pull azul/zulu-openjdk-alpine:17-jre" already has amd64 and arm64 support, it should be as simple as adding TARGETOS/TARGETARCH to your dockerfile. You could check out itzg's Dockerfile for Vanilla Minecraft. https://github.com/itzg/docker-minecraft-server/blob/master/Dockerfile

**Comment by automate-this** [comment]
https://docs.docker.com/desktop/multi-arch/

**Comment by mtoensing** [comment]
Would you mind to provide a pull request and test it before that? That would be great! I will the assign the tags on Docker.com

**Comment by automate-this** [comment]
I hope i've done this the right way. 
You might have to enable a new builder to use multi-arch building.
`docker buildx create --use --name multi-arch`

**Comment by automate-this** [comment]
If you are using github actions, you can use buildx there too
https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

**Comment by automate-this** [comment]
somethings still not working. the correct arm64 image gets pulled, but starting it fails with:
`minecraft-mc-1  | exec /opt/minecraft/docker-entrypoint.sh: exec format error`

**Comment by mtoensing** [comment]
Did it work in your branch?
