### ISSUE TITLE
Cannot pull 1.16.5 image

### ISSUE THREAD

**Issue by thisjade** [mtoensing/Docker-Minecraft-PaperMC-Server#60]
Error response from daemon: manifest for marctv/minecraft-papermc-server:1.16.5 not found: manifest unknown: manifest unknown

**Comment by mtoensing** [comment]
Sorry but 16.x is not supported or build anymore in this image. May I ask why you need it so that I can think about bringing it back?

**Comment by thisjade** [comment]
well i got it to work without the subversion number
but some people use different version for client perfomance 
```docker pull marctv/minecraft-papermc-server:1.16``` works and gives me a 1.16.5 server so i guess i can consider this as "fixed"

**Comment by mtoensing** [comment]
This is an old and maybe insecure version. I will remove that from Docker.com because the image may be still vulnerable to Java attacks! Beware!

**Comment by thisjade** [comment]
i got it at least update to Java 16.0.2 and also updated the server jar so i guess im now a bit more secure
