### ISSUE TITLE
Raspberry PI4 error while creating container

### ISSUE THREAD

**Issue by KyrosWeb** [mtoensing/Docker-Minecraft-PaperMC-Server#61]
When execute the command

docker run -d \
--restart unless-stopped \
--name mcserver \
-e MEMORYSIZE='1G' \
-e PAPERMC_FLAGS='' \
-v /home/pi/mcserver:/data:rw \
-p 25565:25565 \
-it marctv/minecraft-papermc-server:latest

This is the Error:
```
Unable to find image 'marctv/minecraft-papermc-server:latest' locally
latest: Pulling from marctv/minecraft-papermc-server
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
```

This is the result of my "uname -a"

`Linux raspberrypi 5.15.56-v8+ #1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022 aarch64 GNU/Linux`

**Comment by mtoensing** [comment]
Please use Raspberry OS 64-Bit. You can use this script https://github.com/mtoensing/RaspberryPiMinecraftDocker or use the tutorial https://marc.tv/minecraft-java-raspberry-pi-docker/

**Comment by KyrosWeb** [comment]
> Please use Raspberry OS 64-Bit. You can use this script https://github.com/mtoensing/RaspberryPiMinecraftDocker or use the tutorial https://marc.tv/minecraft-java-raspberry-pi-docker/

I'm pretty sure i've RP 64-Bit

with "uname -m" the result is
`aarch64`
Thanks for fast reply

**Comment by mtoensing** [comment]
Okay. Then please follow the tutorial in the Readme or use the ready made script. I installed it yesterday on a Pi 64 Bit.

**Comment by mtoensing** [comment]
Is it a Pi 4 or Pi 3 or lower?

**Comment by KyrosWeb** [comment]
It's a Pi 4

**Comment by KyrosWeb** [comment]
Docker is 32 bit!!

i've done file /usr/bin/docker

This is the result

`/usr/bin/docker: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=cceb8a917aebf0612a004dbf8b4ae0c498912876, for GNU/Linux 3.2.0, not stripped`

I've to try to update it without deleting all my containers.

**Comment by mtoensing** [comment]
Okay.I think we can close this.
