### ISSUE TITLE
WebSocket support - 404 WebSocket Upgrade Failure

### ISSUE THREAD

**Issue by EloToJaa** [mtoensing/Docker-Minecraft-PaperMC-Server#62]
When trying to use WebConsole Spigot plugin (https://www.spigotmc.org/resources/webconsole.70370/). I get an **404 WebSocket Upgrade Failure** when trying to connect. The plugin config is probably not the issue. Does this image contain WebSocket support?

**Comment by mtoensing** [comment]
Honestly I don't know. If PaperMC does not use this then most likely not.
