### ISSUE TITLE
version

### ISSUE THREAD

**Issue by I-am-Piter** [mtoensing/Docker-Minecraft-PaperMC-Server#63]
even if i type 1.19 version, it downloads newest, pls help

**Comment by mtoensing** [comment]
The tag 1.19 will provide you with the latest 1.19 which is 1.19.2

**Comment by I-am-Piter** [comment]
How to install strict 1.19?

**Comment by mtoensing** [comment]
Not possible. What is the reason that you want that?

**Comment by mtoensing** [comment]
Yeah but 1.19.2 is better

**Comment by I-am-Piter** [comment]
its newer, i don't know if it's better

**Comment by viperdriver2000** [comment]
can you update to 1.19.3 ?

**Comment by mtoensing** [comment]
It runs already on 1.19.3

**Comment by viperdriver2000** [comment]
yes was my mistake. the container not update correctly. sorry for the comment
