### ISSUE TITLE
QUESTION :  Email notification when Users Log In

### ISSUE THREAD

**Issue by siw1973** [mtoensing/Docker-Minecraft-PaperMC-Server#65]
A question rather than an issue.

Is it possible to set up email notification when Users login to the Minecraft World providing the date, time, Username and outcome / error message?

It looks like the logs are in logs.db file?

**Comment by vladislav06** [comment]
This is plugin job, not container

**Comment by mtoensing** [comment]
Yes. You have to install a plug-in for that.

**Comment by siw1973** [comment]
Hi there, any guidance or point me in the direction of where to look ?

> This is plugin job, not container



> Yes. You have to install a plug-in for that.
