### ISSUE TITLE
WebP Support

### ISSUE THREAD

**Issue by ryan5453** [mtoensing/Docker-Minecraft-PaperMC-Server#66]
Hi, I was wondering it if was possible to add WebP support to the docker image. This is used for Dynmap.

It looks like this is an Ubuntu image behind the scenes, so you should just be able to `apt-get install -y webp`

Thanks!

**Comment by mtoensing** [comment]
Okay. But why?

**Comment by ryan5453** [comment]
WebP images are much smaller and higher quality than other image formats

**Comment by mtoensing** [comment]
I know. But why don’t you use Overviewer https://hub.docker.com/r/marctv/minecraft-overviewer
