### ISSUE TITLE
Daily rebuild of image causes watchtower to update the container every day

### ISSUE THREAD

**Issue by laugmanuel** [mtoensing/Docker-Minecraft-PaperMC-Server#68]
This is more like a question than an issue but it would be nice to hear, how everyone else is handling this:

I'm using watchtower to keep the docker images I run up2date. Due to the daily rebuild of this image (and the new ref), watchtower is updating the container every single day - even if there are no changes inside the image.

How do you do this in your setup? Just live with it, update manually, ...?

**Comment by mtoensing** [comment]
I love with that. Normally there should be updates of PaperMC every day

**Comment by laugmanuel** [comment]
Maybe there is indeed a change and I just did not notice it so far.
Thanks for the repsonse!
