### ISSUE TITLE
Version 1.19 of the Docker Hub image fails on AMD Ubuntu 20.04

### ISSUE THREAD

**Issue by cshotton** [mtoensing/Docker-Minecraft-PaperMC-Server#69]
Using the basic "read me" command line to launch the latest image of the PaperMC-Server via Docker on Ubuntu Server 20.04, with an empty data folder, results in:
```
[0.023s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: 
 stacksize: 1024k, guardsize: 4k, detached.
 #
 # There is insufficient memory for the Java Runtime Environment to continue.
 # Cannot create worker GC thread. Out of system resources.
 # An error report file with more information is saved as:
 # /data/hs_err_pid1.log
```
Reverting to the tagged 1.18 version runs fine on the same machine and O/S, again with an empty data directory.

Something significant has changed in the current build that makes it no longer compatible with previous installs.

**Comment by mtoensing** [comment]
You have your answer right there: 

_There is insufficient memory for the Java Runtime Environment to continue._ 

Please assign more ram the more recent version of Paper MC used in this container
