### ISSUE TITLE
Update to 1.16.1

### ISSUE THREAD

**Issue by tidalvirus** [mtoensing/Docker-Minecraft-PaperMC-Server#7]
Was just wondering how much effort it might take to get 1.16.1 working in a docker container - still new to this docker thing here. Wondering if just modifying the Dockerfile is all that's needed, or if there might be more work involved. I see some diffs where some modifications happened and got reverted. Hints/tips gladly received!

**Comment by mtoensing** [comment]
1.16 is not stable yet. I will update my container when I use it in production myself. Right now you can and will destroy your world.

**Comment by mtoensing** [comment]
Done. There is now 1.16 tag. After some testing over the weekend this branch will be merged into latest.

**Comment by tidalvirus** [comment]
Thank you kind sir! I shall wait til the weekend :)
