### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by TerraBartz** [mtoensing/Docker-Minecraft-PaperMC-Server#70]
So, I recently installed PaperMC through Docker Hub and ran it once. Then I ran it again the next day just to see this error. (https://pastebin.com/dAbk2mnF)
 The PaperMC tag I was using is 1.16.
I was sure to add *'sudo'* to the command.
Thank you for helping me.

**Comment by mtoensing** [comment]
java.nio.file.AccessDeniedException: /data/./world

Follow the instructions carefully. You have missing permisions
