### ISSUE TITLE
java terminal ?

### ISSUE THREAD

**Issue by garobcsi** [mtoensing/Docker-Minecraft-PaperMC-Server#71]
How do get into the java terminal from your project ?

**Comment by Ronimjan** [comment]
Having issues with this aswell.
When attaching to this container via usual "docker attach [container-name], the commands have no effect.
The only action that works is CTRL+C, which shuts down the server aka. exits the currently in this shell running process.

I don't rly get how to - for example - add people to a whilelist in general via the terminal approach with this image :/

**Comment by DawalaDeny** [comment]
same issue, can't execute commands

**Comment by mtoensing** [comment]
Did you try to remove this parameter?

PAPERMC_FLAGS = --nojline

Sets the command-line flags for PaperMC. Remove --nojline if you want to enable color and tab-completion for the server console.

**Comment by Ronimsenn** [comment]
Hey,
I am not hosting the server anymore.
However, my problem wasn't that I had no color and tab completion for the server console. My problem was, that there was no server console/I couldn't execute commands in it (not 100% sure anymore).

Like, when I executed "stop" (I think thats a valid command?), just nothing happend.

**Comment by mtoensing** [comment]
Yes, I understand that. But this parameter can be the cause for that. You see, this container ist optimized for Synology NAS and runs well on Raspberry Pi, too. This is the environment where it is used the most and tested by myself. So if there is a problem, remove that parameter. In the end this is just a preconfigured Linux that runs in a container with some parameters. :)

**Comment by Ronimsenn** [comment]
I see.

As I said, I do not host it anymore, but I think I tried using/not using the parameter too.
I know for sure I stumbled over it while trying to solve this, since I heard the parameter name before, maybe @DawalaDeny can give more input on this :)

**Comment by DawalaDeny** [comment]
Hey,
i'm running the container on ubuntu via yml file:
  GNU nano 6.2                                                                  docker-compose.yml
version: '3'
services:
  minecraft:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - MEMORYSIZE=16G
    volumes:
      - /home/ubuntu/docker/minecraft_server/data:/data
      **the server is running. 'docker attach mcserver' works, i can see players joining, leaving, etc. But when i type something like 'list' or 'help', nothing happends.

**Comment by Ronimsenn** [comment]
If I remember right, it was basically the same for me. Got the status reports/logs but input didn't work correctly.
Ran Ubuntu 22.04 I think.

**Comment by mtoensing** [comment]
Please try to set PAPERMC_FLAGS to An empty value.

**Comment by DawalaDeny** [comment]
ubuntu@server:~/docker/minecraft_server$ sudo docker attach mcserver
[15:15:49 INFO]: azafun lost connection: Disconnected
[15:15:50 INFO]: azafun left the game
list
[15:15:59 INFO]: UUID of player azafun is 99d714f9-471a-4c6b-89c7-e2c17c8c3413
[15:15:59 INFO]: azafun joined the game
[15:15:59 INFO]: azafun[/socket] logged in with entity id 623 at ([world]1384.3292102238825, 113.9375, -1904.5720461302164)
help
list
stop
[15:16:23 INFO]: azafun lost connection: Disconnected
[15:16:23 INFO]: azafun left the game

version: '3'
services:
  minecraft:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - MEMORYSIZE=16G
      - PAPERMC_FLAGS=
    volumes:
      - /home/ubuntu/docker/minecraft_server/data:/data

still the same issue

**Comment by DawalaDeny** [comment]
okay i tried to do it without yml file, just with the commandline:
sudo docker run -d \
--restart unless-stopped \
--name mcserver \
-e MEMORYSIZE='16G' \
-e PAPERMC_FLAGS='' \
-v /home/ubuntu/docker/minecraft_server/data:/data:rw \
-p 25565:25565 \
-it marctv/minecraft-papermc-server:latest

why doesn't it work with the yml file?

**Comment by mtoensing** [comment]
```
version: '3'
services:
  minecraft:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    ports:
    - 25565:25565
    environment:
    - MEMORYSIZE=16G
    - PAPERMC_FLAGS=""
    volumes:
    - /home/ubuntu/docker/minecraft_server/data:/data
```

You used PAPERMC_FLAGS = " which is not correct

**Comment by Ronimsenn** [comment]
so the correct way would be:


```docker
version: '3'
services:
minecraft:
image: marctv/minecraft-papermc-server:latest
container_name: mcserver
restart: unless-stopped
ports:
- 25565:25565
environment:
- MEMORYSIZE=16G
- PAPERMC_FLAGS=""
volumes:
- /home/ubuntu/docker/minecraft_server/data:/data```

**Comment by DawalaDeny** [comment]
i tried different ways:
- PAPERMC_FLAGS=""
- PAPERMC_FLAGS=" "
- PAPERMC_FLAGS=''
- PAPERMC_FLAGS=

none work, when attached, it doesn't let me execute commands.
the only way it works is without the yml file:
`sudo docker run -d \
--restart unless-stopped \
--name mcserver \
-e MEMORYSIZE='16G' \
-e PAPERMC_FLAGS='' \
-v /home/ubuntu/docker/minecraft_server/data:/data:rw \
-p 25565:25565 \
-it marctv/minecraft-papermc-server:latest `

**Comment by dav473programer** [comment]
i seen that some tutorials use -d and -it and when i tried attaching the container it worked perfectly

**Comment by isatsam** [comment]
FYI, docker-compose is to be deprecated after this month (June 2023) (source: https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/). 
Use `docker compose up` (no dash between docker and compose) instead.

This docker-compose.yml file in the repository works fine for me, including the Java terminal functionality: https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/blob/latest/docker-compose.yaml
Notice the last two lines (they seem to be missing in all .yml files in this thread, assuming those were copypasted in their entirety). 
I checked in my instance that if I comment those out and restart the container, then `docker attach mcserver` will also stop working for me. So they seem to be essential. Hope this helps anyone.

(edit to add the source for docker-compose deprecation)
