### ISSUE TITLE
QUESTION : Macvlan and static IP.

### ISSUE THREAD

**Issue by siw1973** [mtoensing/Docker-Minecraft-PaperMC-Server#72]
Hi, again a question for you....... Sorry !

**OLD LAYOUT**
- Synology Docker installed
- I have two standard Minecraft Paper Servers set up on separate docker containers with differing external ports to the internal MC ports
- I have separate external subdomains set up for both MC servers
- External users use the sub domain / external container port combination with inbound routing via Unifi Port Forwarding to the Synology NAS IP, which then does the routing to the containers based on the port number
ISSUES
- The containers sit on my main subnet as my Synology server and all the other core servers / PCs, I do have a separate IoT subnet
- VLAN / Guest Access is not possible to the Servers when other people are using wifi in my house as I have blocked access to the Core network
- Guests have to be provided with the Core Wifi credentials to play MC in our house

**NEW LAYOUT**
- I have added a new Synology network interface to the IoT / non core network assigned to a single LAN port, which is VLAN tagged
- I have set up a Macvlan using portainer (hosted in a Synology Docker container) which is linked to a specific IP Range of the IoT network (192.168.2.224 upwards)
- Each MC Container on startup gets allocated a external IP starting from 192.168.2.224 based on container start up order........
- I have routed the sub domain / external container port combination with inbound routing via Unifi Port Forwarding directly to the Container 192.168.2.x and use the standard internal MC ports
- On the guest network I have allowed direct access from it's subnet to the specific IP addresses of the two containers on the IoT network
ISSUE
- The containers do not have either a static IP or static MAC address as they are just added in sequence from Docker.
- I can try and control the order in which the containers a Run, to ensure that the two containers retain their specific IPs that are used in the Unifi Port Forwarding, but this requires me to remember things...... 

**QUESTION**
Finally the question you say.......

Is there an ability to setup a Docker Paper MC container via the Synology Docker UI that I can assign a static IP / MAC address using the Environment or Command Variables ?

**Comment by mtoensing** [comment]
I understand your problem, but this is not within the scope of this container. Since you can configure everything in this simple container this should work but I don't know how.

**Comment by siw1973** [comment]
For reference in Portainer you can fully duplicate a container and when setting up the duplicate you can point this to the Macvlan and specify the IP address.

Containers created in Portainer need a Synology Docker restart to be displayed and then the old Container can be deleted.
