### ISSUE TITLE
run commands non-interactively

### ISSUE THREAD

**Issue by TheMemeSniper** [mtoensing/Docker-Minecraft-PaperMC-Server#74]
i would like a way to run commands non-interactively so an automated update script can warn the players about the update, wait a minute, then stop the container, destroy it, pull the new image, and then start the server again.

the [other docker image](https://github.com/itzg/docker-minecraft-server), has an "mc-send-to-console" script bundled with the image, but i don't use it because it isn't updated as often as this one.

could we get something like this?

**Comment by mtoensing** [comment]
I really like to keep this simple. Can you use the bundled RCON CLI for that?

**Comment by TheMemeSniper** [comment]
i really don't want to expose RCON, even just to my local network.

**Comment by mtoensing** [comment]
But can't you control that with the ports?

**Comment by TheMemeSniper** [comment]
i don't understand what you mean by "with the ports".

**Comment by mtoensing** [comment]
Isn't there an rcon Port you need to expose externally?

**Comment by TheMemeSniper** [comment]
i have my server in host network mode and yes i do need to use port forwarding to expose it to the internet but i would also like to keep RCON closed on the local network and the internet

**Comment by mtoensing** [comment]
Maybe I really don't get it but can't you forward the Mcserver ports to the router and leave rcon locally? And then write a script that uses rcon locally?

**Comment by TheMemeSniper** [comment]
that's the problem, i don't want to use RCON.

**Comment by mtoensing** [comment]
Okay, but you may understand that I don't want to add complexity by adding another way for the same task

**Comment by TheMemeSniper** [comment]
ok
