### ISSUE TITLE
An internal error occurred while  attempting to perform this command

### ISSUE THREAD

**Issue by mikamoenchmeier** [mtoensing/Docker-Minecraft-PaperMC-Server#77]
I just spun up a miner craft server in docker and everything works fine but as soon as I want to enter a command I get this error:
An internal error occurred while  attempting to perform this command

**Comment by mtoensing** [comment]
The server works and commands work to. I can't support the server itself. Maybe some more information would be great or someone else has an idea.

**Comment by mikamoenchmeier** [comment]
Thanks, sorry for taking up your time I'll try somewhere else.

**Comment by mikamoenchmeier** [comment]
Thanks, sorry for taking up your time I'll try somewhere else.

**Comment by mikamoenchmeier** [comment]
Thanks, sorry for taking up your time I'll try somewhere else.
