### ISSUE TITLE
auto updated with no way to rollback and no granular version control options

### ISSUE THREAD

**Issue by necrorika** [mtoensing/Docker-Minecraft-PaperMC-Server#85]
Just what it sounds like. everything was fine, I stop the server for a minute and turn it back on and it's updated to 1.19.4. No way to roll back to 1.19.2. 

From what I can tell you only keep the newest subversion of that major version. I see no way even if I went and replaced it to get it back to 1.19.2. Didn't want to update because I'm not re downloading 30 mods for another version.

**Comment by mtoensing** [comment]
I would like to keep it very simple. This container is for people who just want to play and not tinkle with mods and dependencies.
