### ISSUE TITLE
1.20 Server crashes after start

### ISSUE THREAD

**Issue by Faylamoon** [mtoensing/Docker-Minecraft-PaperMC-Server#86]
I could need your help.
With me on my Syno DS218+, the sever crashes every time, shortly after the start.
Error message is "Sever stopped unexpectedly. See docker for more information."
Unfortunately, I can't look into the terminal either because it says "Socket closed"
Assigned 3-4GB to the server of 16gb
and I completely followed the video instructions and also want to install the 1.20 version.

I am attaching a txt file with the log
what I could already read is that he cannot download the mojang_1.20.jar

[MinecraftServer_1.20 Protokoll.txt](https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/files/12083131/MinecraftServer_1.20.Protokoll.txt)

Sorry I translated everything with Google translator because unfortunately I only speak German

No matter which version I try, it always fails when downloading the Jar. file.
What I've already tried is to turn off my PiHole, but unfortunately that didn't help either.

**Comment by Faylamoon** [comment]
No matter which version I try, it always fails when downloading the Jar. file.
What I've already tried is to turn off my PiHole, but unfortunately that didn't help either.

**Comment by mtoensing** [comment]
I think your problems has to do with the internet connection of the container.

**Comment by Faylamoon** [comment]
> Ich denke, Ihre Probleme hängen mit der Internetverbindung des Containers zusammen.

Okay and how do I find out or fix the problem?

**Comment by Faylamoon** [comment]
ahh okay if I deactivate the bridge mode, which was not in the instructions because you can no longer specify ports, it works.
EULA = true Unfortunately also missing in the parameters
