### ISSUE TITLE
Unable to edit files/add files to folders

### ISSUE THREAD

**Issue by splittah** [mtoensing/Docker-Minecraft-PaperMC-Server#87]
Unable to edit setting files or add plugins to folder due to folders being locked to dockergroup and dockeruser ID 9001:9001.
I can add them using root access but that seems ridiculous when adding plugins jars and editing setting files.
Adding `-e PUID=99 -e PGID=100` to the docker run command to set ownership and group to nobody and users brings up an error of `addgroup: The GID 100' is already in use.`

Not sure what the best practice here is.

**Comment by mtoensing** [comment]
This is a normal docker behavior that has nothing to do with this specific container.
