### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by 3ntropie** [mtoensing/Docker-Minecraft-PaperMC-Server#90]
Hello Marc,

sorry for bothering you. But since you closed the issue and I don't get it, I have to ask you again.

[https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/issues/89](https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/issues/89)

Just a little push in the right direction might help.

**Comment by mtoensing** [comment]
https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server#environment-variables =)

**Comment by 3ntropie** [comment]
Just for documentation. To solve this issue I'v created a file named "mcserver.sh" in the folder "/etc/profile.d/" with the following contents:
export MEMORYSIZE=6G

I'v choosen 6G since my Raspberry has 8GB Memory and I want some spare memory for the OS and some other service running on it. So far the Minecraft server runs fine.
