### ISSUE TITLE
Keeping 1.20.1?

### ISSUE THREAD

**Issue by f4s249211** [mtoensing/Docker-Minecraft-PaperMC-Server#92]
Hello
So, I was using the latest image: "image: marctv/minecraft-papermc-server:latest", with the paper version 1.20.1, recently I restarted the server and it updated to 1.20.2, so how can I keep using the 1.20.1? I already tried "image: marctv/minecraft-papermc-server:1.20.1" but it doesn't work.
Thanks in advance.

**Comment by mtoensing** [comment]
You can’t. The image does not distinguish between 1.20 or 1.20.2
