### ISSUE TITLE
The GID `XXX' is already in use.

### ISSUE THREAD

**Issue by uniks** [mtoensing/Docker-Minecraft-PaperMC-Server#93]
I'm trying to start server with different uid/gid (which of course already exists in my system):

└(0)# docker run --rm --name mcserver -e MEMORYSIZE='1G' -e PUID=1001 -e PGID=100 -v /srv/dev-disk-by-uuid-c74a07be-4b66-4072-b930-9510055e4703/minecraft-data:/data:rw -p 25565:25565 -i marctv/minecraft-papermc-server:latest
First start of the docker container, start initialization process.
Starting with 1001:100 (UID:GID)
addgroup: The GID `100' is already in use.

**Comment by mtoensing** [comment]
I think you have to add the environment variable from the "Skip permission change step" in the read me https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server/blob/latest/README.md#skip-permission-change-step
