### ISSUE TITLE
Unable to find image 'marctv/minecraft-papermc-server:1.20.1' locally docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2600:1f18:2148:bc01:a3b0:6734:c617:7c5c]:443: connect: connection refused. See 'docker run --help'.

### ISSUE THREAD

**Issue by salrn** [mtoensing/Docker-Minecraft-PaperMC-Server#94]
if i run the command: 
docker run -d -it --name mcserver --restart=unless-stopped -e MEMORYSIZE='4G' -v /home/haven/mc-docker:/data:rw -p 25565:25565 -i marctv/minecraft-papermc-server:1.20.1

, i return with this error: 

Unable to find image 'marctv/minecraft-papermc-server:1.20.1' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2600:1f18:2148:bc01:a3b0:6734:c617:7c5c]:443: connect: connection refused.
See 'docker run --help'.

**Comment by mtoensing** [comment]
This is a local problem with your internet. Ask ChatGPT.
