### ISSUE TITLE
Automatically update the 1.20 tag in docker hub

### ISSUE THREAD

**Issue by rrvk** [mtoensing/Docker-Minecraft-PaperMC-Server#95]
When you look at the tags in docker hub you can see that the 1.20 tag is verry old and if you really want to use the 1.20 mc version you need to be on the latest tag.

It would be very nice if the 1.20 tag is also updated regularly (best automatically), this so you won't be upgraded to the next major version when it comes out and will be pushed to the latest tag

**Comment by mtoensing** [comment]
Yes, I know. If someone has an idea to update the tags via GitHub actions, please let me know or provide a MR.

**Comment by rrvk** [comment]
I will readup on github actions and try to fix it :)
